name: Fuzzer Image CI

on:
  push:
    branches: [ "master" ]
    # tags: type=sha,format=long
  pull_request:
    branches: [ "master" ]
    # tags: type=sha,format=long
  workflow_dispatch:


env:
  REGISTRY: ghcr.io
  #IMAGE_NAME: ${{ fuzzheur }}
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build-and-push-image:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: 
          ${{ github.sha }}
        #   type=sha,format=long
        #   type=raw,value=latest
        flavor: latest=true

    # - name: Build the fuzzer image

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Run fuzzer and upload fuzzer output as artifact
      run: |
        mkdir -p ${{ github.workspace }}/output
        docker run --rm -v ${{ github.workspace }}/output:/output ${{ env.REGISTRY }}/${{  env.IMAGE_NAME  }}:latest
    - uses: actions/upload-artifact@v3
      with:
        name: fuzzer-output
        path: ${{ github.workspace }}/output
        compression-level: 6 #default