name: Fuzzer Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:


env:
  REGISTRY: ghcr.io
  #IMAGE_NAME: ${{ fuzzheur }}
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build-and-push-image:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # - name: Extract metadata (tags, labels) for Docker
    #    id: meta
    #    uses: docker/metadata-action@v3
    #    with:
    #      images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    # - name: Build the fuzzer image

    - name: Build and push Docker image
        # id: push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          # tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}
      # - run: docker build --file Dockerfile --tag malheur .

    # - name: Push image
    # - run: docker tag
    #     IMAGE_ID=${{ env.REGISTRY }}/${{ github.repository_owner }}/${{  env.IMAGE_NAME  }}

    #     docker tag ${{ env.IMAGE_NAME }} $IMAGE_ID:latest
    #     docker push $IMAGE_ID:latest
